# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - EFSM-webapp-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # Build on Linux so node_modules match Linux App Service runtime
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        env:
          NEXT_PUBLIC_AZURE_AD_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AZURE_AD_CLIENT_ID }}
          NEXT_PUBLIC_AZURE_AD_TENANT_ID: ${{ secrets.NEXT_PUBLIC_AZURE_AD_TENANT_ID }}
          NEXT_PUBLIC_AZURE_AD_AUTHORITY: ${{ secrets.NEXT_PUBLIC_AZURE_AD_AUTHORITY }}
          NEXT_PUBLIC_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}
          NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI }}
          NEXT_PUBLIC_KNOWN_AUTHORITY: ${{ secrets.NEXT_PUBLIC_KNOWN_AUTHORITY }}
          NODE_ENV: production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            package.json
            package-lock.json
            next.config.ts
            server.js
            web.config
            public
            .next
            node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F394749E68604AF0837359A72218D64F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DF334475E8BD4AF990EE014E4C4FCF75 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_39D71AF96C9B4D3B91D945340FE2C4E4 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EFSM-webapp-dev'
          slot-name: 'Production'
          package: .
          startup-command: 'node server.js'

      - name: 'Set Azure Web App Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'EFSM-webapp-dev'
          slot-name: 'Production'
          app-settings-json: |
            [
              {
                "name": "NEXT_PUBLIC_AZURE_AD_CLIENT_ID",
                "value": "${{ secrets.NEXT_PUBLIC_AZURE_AD_CLIENT_ID }}"
              },
              {
                "name": "NEXT_PUBLIC_AZURE_AD_TENANT_ID", 
                "value": "${{ secrets.NEXT_PUBLIC_AZURE_AD_TENANT_ID }}"
              },
              {
                "name": "NEXT_PUBLIC_AZURE_AD_AUTHORITY", 
                "value": "${{ secrets.NEXT_PUBLIC_AZURE_AD_AUTHORITY }}"
              },
              {
                "name": "NEXT_PUBLIC_REDIRECT_URI",
                "value": "${{ secrets.NEXT_PUBLIC_REDIRECT_URI }}"
              },
              {
                "name": "NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI",
                "value": "${{ secrets.NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI }}"
              },
              {
                "name": "NEXT_PUBLIC_KNOWN_AUTHORITY",
                "value": "${{ secrets.NEXT_PUBLIC_KNOWN_AUTHORITY }}"
              },
              {
                "name": "NODE_ENV",
                "value": "production"
              },
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "~22"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "false"
              },
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "1"
              }
            ]

      - name: Restart Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart --name EFSM-webapp-dev --resource-group efsm-dev
          